### ISSUE TITLE
CSS滤镜(filter)使用场景

### ISSUE THREAD

**Issue by jwenjian** [jwenjian/ghiblog#153]
CSS的filter属性，可以为HTML元素加上滤镜效果。常用的滤镜效果：

---

- 页面变黑白
![image](https://user-images.githubusercontent.com/25657798/70840434-3775bf00-1e4d-11ea-99ef-140965ad69c4.png)

```css
html {
  filter: greyscale(1)
}
```

- 背景高斯模糊
![image](https://user-images.githubusercontent.com/25657798/70840520-bc60d880-1e4d-11ea-813d-a4305391467b.png)

```css
html {
  filter: blur(5px)
}
```

- 调整透明度
![image](https://user-images.githubusercontent.com/25657798/70840545-f3cf8500-1e4d-11ea-94d6-8236556eec4b.png)

```css
html {
  filter: opacity(0.5)
}
```

---

- [filter - CSS（层叠样式表） | MDN](https://developer.mozilla.org/zh-CN/docs/Web/CSS/filter)
